define(function () {
    'use strict';
    __touch(18782);
    function ShaderFragment() {
    }
    __touch(18783);
    ShaderFragment.noisecommon = [
        'vec4 mod289(vec4 x) {',
        '  return x - floor(x * (1.0 / 289.0)) * 289.0;',
        '}',
        'vec3 mod289(vec3 x) {',
        '  return x - floor(x * (1.0 / 289.0)) * 289.0;',
        '}',
        'vec2 mod289(vec2 x) {',
        '  return x - floor(x * (1.0 / 289.0)) * 289.0;',
        '}',
        'vec3 permute(vec3 x) {',
        '  return mod289(((x*34.0)+1.0)*x);',
        '}',
        'vec4 permute(vec4 x) {',
        '  return mod289(((x*34.0)+1.0)*x);',
        '}'
    ].join('\n');
    __touch(18784);
    ShaderFragment.noise2d = [
        ShaderFragment.noisecommon,
        'float snoise(vec2 v)',
        '  {',
        '  const vec4 C = vec4(0.211324865405187,  // (3.0-sqrt(3.0))/6.0',
        '                      0.366025403784439,  // 0.5*(sqrt(3.0)-1.0)',
        '                     -0.577350269189626,  // -1.0 + 2.0 * C.x',
        '                      0.024390243902439); // 1.0 / 41.0',
        '  vec2 i  = floor(v + dot(v, C.yy) );',
        '  vec2 x0 = v -   i + dot(i, C.xx);',
        '  vec2 i1;',
        '  //i1.x = step( x0.y, x0.x ); // x0.x > x0.y ? 1.0 : 0.0',
        '  //i1.y = 1.0 - i1.x;',
        '  i1 = (x0.x > x0.y) ? vec2(1.0, 0.0) : vec2(0.0, 1.0);',
        '  // x0 = x0 - 0.0 + 0.0 * C.xx ;',
        '  // x1 = x0 - i1 + 1.0 * C.xx ;',
        '  // x2 = x0 - 1.0 + 2.0 * C.xx ;',
        '  vec4 x12 = x0.xyxy + C.xxzz;',
        '  x12.xy -= i1;',
        '  i = mod289(i); // Avoid truncation effects in permutation',
        '  vec3 p = permute( permute( i.y + vec3(0.0, i1.y, 1.0 ))',
        '\t\t+ i.x + vec3(0.0, i1.x, 1.0 ));',
        '  vec3 m = max(0.5 - vec3(dot(x0,x0), dot(x12.xy,x12.xy), dot(x12.zw,x12.zw)), 0.0);',
        '  m = m*m ;',
        '  m = m*m ;',
        '  vec3 x = 2.0 * fract(p * C.www) - 1.0;',
        '  vec3 h = abs(x) - 0.5;',
        '  vec3 ox = floor(x + 0.5);',
        '  vec3 a0 = x - ox;',
        '  m *= 1.79284291400159 - 0.85373472095314 * ( a0*a0 + h*h );',
        '  vec3 g;',
        '  g.x  = a0.x  * x0.x  + h.x  * x0.y;',
        '  g.yz = a0.yz * x12.xz + h.yz * x12.yw;',
        '  return 130.0 * dot(m, g);',
        '}'
    ].join('\n');
    __touch(18785);
    ShaderFragment.noise3d = [
        ShaderFragment.noisecommon,
        'vec4 taylorInvSqrt(vec4 r) {',
        '\treturn 1.79284291400159 - 0.85373472095314 * r;',
        '}',
        'float snoise(vec3 v) {',
        '\tconst vec2  C = vec2(1.0/6.0, 1.0/3.0) ;',
        '\tconst vec4  D = vec4(0.0, 0.5, 1.0, 2.0);',
        '\tvec3 i  = floor(v + dot(v, C.yyy) );',
        '\tvec3 x0 =   v - i + dot(i, C.xxx) ;',
        '\tvec3 g = step(x0.yzx, x0.xyz);',
        '\tvec3 l = 1.0 - g;',
        '\tvec3 i1 = min( g.xyz, l.zxy );',
        '\tvec3 i2 = max( g.xyz, l.zxy );',
        '\tvec3 x1 = x0 - i1 + C.xxx;',
        '\tvec3 x2 = x0 - i2 + C.yyy; // 2.0*C.x = 1/3 = C.y',
        '\tvec3 x3 = x0 - D.yyy;      // -1.0+3.0*C.x = -0.5 = -D.y',
        '\ti = mod289(i); ',
        '\tvec4 p = permute( permute( permute( ',
        '         i.z + vec4(0.0, i1.z, i2.z, 1.0 ))',
        '       + i.y + vec4(0.0, i1.y, i2.y, 1.0 )) ',
        '       + i.x + vec4(0.0, i1.x, i2.x, 1.0 ));',
        '\tfloat n_ = 0.142857142857; // 1.0/7.0',
        '\tvec3  ns = n_ * D.wyz - D.xzx;',
        '\tvec4 j = p - 49.0 * floor(p * ns.z * ns.z);  //  mod(p,7*7)',
        '\tvec4 x_ = floor(j * ns.z);',
        '\tvec4 y_ = floor(j - 7.0 * x_ );    // mod(j,N)',
        '\tvec4 x = x_ *ns.x + ns.yyyy;',
        '\tvec4 y = y_ *ns.x + ns.yyyy;',
        '\tvec4 h = 1.0 - abs(x) - abs(y);',
        '\tvec4 b0 = vec4( x.xy, y.xy );',
        '\tvec4 b1 = vec4( x.zw, y.zw );',
        '\tvec4 s0 = floor(b0)*2.0 + 1.0;',
        '\tvec4 s1 = floor(b1)*2.0 + 1.0;',
        '\tvec4 sh = -step(h, vec4(0.0));',
        '\tvec4 a0 = b0.xzyw + s0.xzyw*sh.xxyy ;',
        '\tvec4 a1 = b1.xzyw + s1.xzyw*sh.zzww ;',
        '\tvec3 p0 = vec3(a0.xy,h.x);',
        '\tvec3 p1 = vec3(a0.zw,h.y);',
        '\tvec3 p2 = vec3(a1.xy,h.z);',
        '\tvec3 p3 = vec3(a1.zw,h.w);',
        '\tvec4 norm = taylorInvSqrt(vec4(dot(p0,p0), dot(p1,p1), dot(p2, p2), dot(p3,p3)));',
        '\tp0 *= norm.x;',
        '\tp1 *= norm.y;',
        '\tp2 *= norm.z;',
        '\tp3 *= norm.w;',
        '\tvec4 m = max(0.6 - vec4(dot(x0,x0), dot(x1,x1), dot(x2,x2), dot(x3,x3)), 0.0);',
        '\tm = m * m;',
        '\treturn 42.0 * dot( m*m, vec4( dot(p0,x0), dot(p1,x1), dot(p2,x2), dot(p3,x3) ) );',
        '}'
    ].join('\n');
    __touch(18786);
    ShaderFragment.methods = {
        packDepth: [
            'vec4 packDepth( const in float depth ) {',
            '\tconst vec4 bit_shift = vec4( 256.0 * 256.0 * 256.0, 256.0 * 256.0, 256.0, 1.0 );',
            '\tconst vec4 bit_mask  = vec4( 0.0, 1.0 / 256.0, 1.0 / 256.0, 1.0 / 256.0 );',
            '\tvec4 res = fract( depth * bit_shift );',
            '\tres -= res.xxyz * bit_mask;',
            '\treturn res;',
            '}'
        ].join('\n'),
        unpackDepth: [
            'float unpackDepth( const in vec4 rgba_depth ) {',
            '\tconst vec4 bit_shift = vec4( 1.0 / ( 256.0 * 256.0 * 256.0 ), 1.0 / ( 256.0 * 256.0 ), 1.0 / 256.0, 1.0 );',
            '\tfloat depth = dot( rgba_depth, bit_shift );',
            '\treturn depth;',
            '}'
        ].join('\n'),
        packDepth16: [
            'vec2 packDepth16( const in float depth ) {',
            '\tconst vec2 bias = vec2(1.0 / 255.0, 0.0);',
            '\tvec2 res = vec2(depth, fract(depth * 255.0));',
            '\treturn res - (res.yy * bias);',
            '}'
        ].join('\n'),
        unpackDepth16: [
            'float unpackDepth16( const in vec2 rg_depth ) {',
            '\treturn rg_depth.x + (rg_depth.y / 255.0);',
            '}'
        ].join('\n'),
        hsv: [
            'vec3 rgb2hsv(vec3 c) {',
            'vec4 K = vec4(0.0, -1.0 / 3.0, 2.0 / 3.0, -1.0);',
            'vec4 p = mix(vec4(c.bg, K.wz), vec4(c.gb, K.xy), step(c.b, c.g));',
            'vec4 q = mix(vec4(p.xyw, c.r), vec4(c.r, p.yzx), step(p.x, c.r));',
            'float d = q.x - min(q.w, q.y);',
            'float e = 1.0e-10;',
            'return vec3(abs(q.z + (q.w - q.y) / (6.0 * d + e)), d / (q.x + e), q.x);',
            '}',
            'vec3 hsv2rgb(vec3 c){',
            'vec4 K = vec4(1.0, 2.0 / 3.0, 1.0 / 3.0, 3.0);',
            'vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);',
            'return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);',
            '}'
        ].join('\n')
    };
    __touch(18787);
    ShaderFragment.blendmodes = [
        '#define BlendLinearDodgef\t\t\t\tBlendAddf',
        '#define BlendLinearBurnf\t\t\t\tBlendSubstractf',
        '#define BlendAddf(base, blend)\t\t\tmin(base + blend, 1.0)',
        '#define BlendSubstractf(base, blend)\tmax(base + blend - 1.0, 0.0)',
        '#define BlendLightenf(base, blend)\t\tmax(blend, base)',
        '#define BlendDarkenf(base, blend)\t\tmin(blend, base)',
        '#define BlendLinearLightf(base, blend)\t(blend < 0.5 ? BlendLinearBurnf(base, (2.0 * blend)) : BlendLinearDodgef(base, (2.0 * (blend - 0.5))))',
        '#define BlendScreenf(base, blend)\t\t(1.0 - ((1.0 - base) * (1.0 - blend)))',
        '#define BlendOverlayf(base, blend)\t\t(base < 0.5 ? (2.0 * base * blend) : (1.0 - 2.0 * (1.0 - base) * (1.0 - blend)))',
        '#define BlendSoftLightf(base, blend)\t((blend < 0.5) ? (2.0 * base * blend + base * base * (1.0 - 2.0 * blend)) : (sqrt(base) * (2.0 * blend - 1.0) + 2.0 * base * (1.0 - blend)))',
        '#define BlendColorDodgef(base, blend)\t((blend == 1.0) ? blend : min(base / (1.0 - blend), 1.0))',
        '#define BlendColorBurnf(base, blend)\t((blend == 0.0) ? blend : max((1.0 - ((1.0 - base) / blend)), 0.0))',
        '#define BlendVividLightf(base, blend)\t((blend < 0.5) ? BlendColorBurnf(base, (2.0 * blend)) : BlendColorDodgef(base, (2.0 * (blend - 0.5))))',
        '#define BlendPinLightf(base, blend)\t((blend < 0.5) ? BlendDarkenf(base, (2.0 * blend)) : BlendLightenf(base, (2.0 *(blend - 0.5))))',
        '#define BlendHardMixf(base, blend)\t\t((BlendVividLightf(base, blend) < 0.5) ? 0.0 : 1.0)',
        '#define BlendReflectf(base, blend)\t\t((blend == 1.0) ? blend : min(base * base / (1.0 - blend), 1.0))',
        '#define Blend(base, blend, funcf)\t\tvec3(funcf(base.r, blend.r), funcf(base.g, blend.g), funcf(base.b, blend.b))',
        '#define BlendNormal(base, blend)\t\t(blend)',
        '#define BlendLighten\t\t\t\t\tBlendLightenf',
        '#define BlendDarken\t\t\t\t\tBlendDarkenf',
        '#define BlendMultiply(base, blend)\t\t(base * blend)',
        '#define BlendAverage(base, blend)\t\t((base + blend) / 2.0)',
        '#define BlendAdd(base, blend)\t\t\tmin(base + blend, vec3(1.0))',
        '#define BlendSubstract(base, blend)\tmax(base + blend - vec3(1.0), vec3(0.0))',
        '#define BlendDifference(base, blend)\tabs(base - blend)',
        '#define BlendNegation(base, blend)\t\t(vec3(1.0) - abs(vec3(1.0) - base - blend))',
        '#define BlendExclusion(base, blend)\t(base + blend - 2.0 * base * blend)',
        '#define BlendScreen(base, blend)\t\tBlend(base, blend, BlendScreenf)',
        '#define BlendOverlay(base, blend)\t\tBlend(base, blend, BlendOverlayf)',
        '#define BlendSoftLight(base, blend)\tBlend(base, blend, BlendSoftLightf)',
        '#define BlendHardLight(base, blend)\tBlendOverlay(blend, base)',
        '#define BlendColorDodge(base, blend)\tBlend(base, blend, BlendColorDodgef)',
        '#define BlendColorBurn(base, blend)\tBlend(base, blend, BlendColorBurnf)',
        '#define BlendLinearDodge\t\t\t\tBlendAdd',
        '#define BlendLinearBurn\t\t\t\tBlendSubstract',
        '#define BlendLinearLight(base, blend)\tBlend(base, blend, BlendLinearLightf)',
        '#define BlendVividLight(base, blend)\tBlend(base, blend, BlendVividLightf)',
        '#define BlendPinLight(base, blend)\t\tBlend(base, blend, BlendPinLightf)',
        '#define BlendHardMix(base, blend)\t\tBlend(base, blend, BlendHardMixf)',
        '#define BlendReflect(base, blend)\t\tBlend(base, blend, BlendReflectf)',
        '#define BlendGlow(base, blend)\t\t\tBlendReflect(blend, base)',
        '#define BlendPhoenix(base, blend)\t\t(min(base, blend) - max(base, blend) + vec3(1.0))',
        '#define GammaCorrection(color, gamma)\t\t\t\t\t\t\t\t\t\t\tpow(color, vec3(1.0 / gamma))',
        '#define LevelsControlInputRange(color, minInput, maxInput)\t\t\t\t\t\tmin(max(color - vec3(minInput), vec3(0.0)) / (vec3(maxInput) - vec3(minInput)), vec3(1.0))',
        '#define LevelsControlInput(color, minInput, gamma, maxInput)\t\t\t\t\tGammaCorrection(LevelsControlInputRange(color, minInput, maxInput), gamma)',
        '#define LevelsControlOutputRange(color, minOutput, maxOutput)\t\t\t\t\tmix(vec3(minOutput), vec3(maxOutput), color)',
        '#define LevelsControl(color, minInput, gamma, maxInput, minOutput, maxOutput)\tLevelsControlOutputRange(LevelsControlInput(color, minInput, gamma, maxInput), minOutput, maxOutput)'
    ].join('\n');
    __touch(18788);
    return ShaderFragment;
    __touch(18789);
});
__touch(18781);