// Generated by CoffeeScript 1.6.2
define(['goo/lib/underscore'], function() {
  var ConsoleUtil, levels, noop, _console;

  _console = null;
  levels = ['debug', 'log', 'info', 'warn', 'error'];
  noop = function() {};
  return ConsoleUtil = {
    /**
    		* Set the log level. Messages with lower urgency will not be printed. Example usage: 
    		* <code>
    		* require (['goo/util/ConsoleUtil'], function(console) {
    		* 	console.setLogLevel('warn');	
    		*		console.log('This message will NOT be printed');
    		* 	console.warn('This warning will be printed');
    		* 	console.clearLogLevel();
    		*		console.log('This message will be printed');
    		* }
    		* </code>
    		* @param {string} newLevel Minimum urgency level. One of <code>['debug','log','info','warn','error']</code> (ordered by priority).
    		*
    */

    setLogLevel: function(newLevel) {
      var level, _i, _len, _results;

      if (_console == null) {
        _console = _.clone(window.console);
      }
      ConsoleUtil.clearLogLevel();
      _results = [];
      for (_i = 0, _len = levels.length; _i < _len; _i++) {
        level = levels[_i];
        if (level === newLevel) {
          break;
        }
        _results.push(window.console[level] = noop);
      }
      return _results;
    },
    /**
    		* Reset the log level. All messages will be printed.
    		*
    */

    clearLogLevel: function() {
      var level, _i, _len, _results;

      if (_console) {
        _results = [];
        for (_i = 0, _len = levels.length; _i < _len; _i++) {
          level = levels[_i];
          _results.push(window.console[level] = _console[level]);
        }
        return _results;
      }
    }
  };
});
