// Generated by CoffeeScript 1.6.2
define([], function() {
  /**
  	* @class Utility to set log levels for the debug console in the browser. Static class. Usage: 
  	* <code>
  	* require (['goo/util/ConsoleUtil'], function(console) {
  	* 	console.setLogLevel('warn');	
  	*		console.log('This message will NOT be printed');
  	* 	console.warn('This warning will be printed');
  	* 	console.clearLogLevel();
  	*		console.log('This message will be printed');
  	* }
  	* </code>
  	*
  	*
  */

  var Console;

  Console = (function() {
    var levels, noop;

    function Console() {}

    levels = ['debug', 'log', 'info', 'warn', 'error'];

    noop = function() {};

    /**
    		* Set the log level. Messages with lower urgency will not be printed.
    		*
    		* @param {string} newLevel Minimum urgency level. One of <code>['debug','log','info','warn','error']</code> (ordered by priority).
    		*
    */


    Console.setLogLevel = function(newLevel) {
      var level, _i, _len, _results;

      this.clearLogLevel();
      _results = [];
      for (_i = 0, _len = levels.length; _i < _len; _i++) {
        level = levels[_i];
        if (level === newLevel) {
          break;
        }
        _results.push(this[level] = noop);
      }
      return _results;
    };

    /**
    		* Reset the log level. All messages will be printed.
    		*
    */


    Console.clearLogLevel = function() {
      var level, _i, _len, _results;

      _results = [];
      for (_i = 0, _len = levels.length; _i < _len; _i++) {
        level = levels[_i];
        _results.push(this[level] = window.console[level]);
      }
      return _results;
    };

    return Console;

  })();
  Console.clearLogLevel();
  return Console;
});
