// Generated by CoffeeScript 1.6.2
define(['goo/util/rsvp'], function(RSVP) {
  return {
    /**
    	* Create a promise that resolves immediately with the given argument.
    	*
    	* @param {any} arg 
    	* @returns {RSVP.Promise}
    	*
    */

    dummyPromise: function(arg) {
      var promise;

      promise = new RSVP.Promise();
      promise.resolve(arg);
      return promise;
    }
  };
});
