// Generated by CoffeeScript 1.6.2
define(['goo/util/ConsoleUtil'], function(console) {
  var ConfigHandler;

  return ConfigHandler = (function() {
    function ConfigHandler(world, getConfig, updateObject) {
      this.world = world;
      this.getConfig = getConfig;
      this.updateObject = updateObject;
    }

    ConfigHandler.handlerClasses = {};

    ConfigHandler.getHandler = function(type) {
      return this.handlerClasses[type];
    };

    ConfigHandler._register = function(type) {
      this._type = type;
      return ConfigHandler.handlerClasses[type] = this;
    };

    return ConfigHandler;

  })();
});
