{
"attributes":{
"vertexColor":"COLOR",
"vertexJointIDs":"JOINTIDS",
"vertexNormal":"NORMAL",
"vertexPosition":"POSITION",
"vertexTangent":"TANGENT",
"vertexUV0":"TEXCOORD0",
"vertexUV1":"TEXCOORD1",
"vertexWeights":"WEIGHTS"
},
"fshaderRef":"shaders/uberShader.frag",
"name":"UberShader",
"processors":[
"uber",
"light",
"animation"
],
"uniforms":{
"aoMap":"AO_MAP",
"cameraPosition":"CAMERA",
"diffuseMap":"DIFFUSE_MAP",
"diffuseRepeat":[
1,
1
],
"emissiveMap":"EMISSIVE_MAP",
"lightMap":"LIGHT_MAP",
"normalMap":"NORMAL_MAP",
"specularMap":"SPECULAR_MAP",
"viewProjectionMatrix":"VIEW_PROJECTION_MATRIX",
"worldMatrix":"WORLD_MATRIX"
},
"vshaderRef":"shaders/uberShader.vert"
}