var path = require('path');
var webpack = require('webpack');

module.exports = function (config) {
  config.set({

	// base path, that will be used to resolve files and exclude
	basePath: '../../',

	plugins: [
		require('karma-jasmine'),
		require('karma-chrome-launcher'),
		require('karma-webpack')
	],

	frameworks: ['jasmine'],

	files: [
		'lib/cannon/cannon.min.js',
		{ pattern: 'test/unit/**/*.mp4', included: false },
		{ pattern: 'test/unit/**/*.png', included: false },
		{ pattern: 'test/unit/**/*-test.js' }
	],

	// list of files to exclude
	exclude: [],

	// test results reporter to use
	// possible values: 'dots', 'progress', 'junit', 'growl', 'coverage'
	reporters: ['dots'/*, 'coverage'*/],


	// web server port
	port: 9876,


	// enable / disable colors in the output (reporters and logs)
	colors: true,


	// level of logging
	// possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
	// logLevel: config.LOG_INFO,


	// enable / disable watching file and executing tests whenever any file changes
	autoWatch: true,


	// Start these browsers, currently available:
	// - Chrome
	// - ChromeCanary
	// - Firefox
	// - Opera (has to be installed with `npm install karma-opera-launcher`)
	// - Safari (only Mac; has to be installed with `npm install karma-safari-launcher`)
	// - PhantomJS
	// - IE (only Windows; has to be installed with `npm install karma-ie-launcher`)
	browsers: ['Chrome'],

	// If browser does not capture in given timeout [ms], kill it
	captureTimeout: 60000,


	// Continuous Integration mode
	// if true, it capture browsers, run tests and exit
	singleRun: false,

	preprocessors: {
		// source files, that you wanna generate coverage for
		// do not include tests or libraries
		// (these files will be instrumented by Istanbul)
		//'**/*.js': [/*'coverage', */'webpack']
		'test/unit/**/*-test.js': ['webpack']
	},

	webpack: {
		resolve: {
			// Everything relative to repo root
			root: path.resolve(path.join(__dirname, '..', '..'))
		},
		plugins: [
			new webpack.ProvidePlugin({
				CustomMatchers: 'test/unit/CustomMatchers',
				Configs: 'test/unit/loaders/Configs',

				PhysicsSystem: 'src/goo/addons/physicspack/systems/PhysicsSystem',
				MathUtils: 'src/goo/math/MathUtils',
				AmmoComponent: 'src/goo/addons/ammopack/AmmoComponent',
				AmmoSystem: 'src/goo/addons/ammopack/AmmoSystem',
				calculateTriangleMeshShape: 'src/goo/addons/ammopack/calculateTriangleMeshShape',
				Box2DComponent: 'src/goo/addons/box2dpack/components/Box2DComponent',
				Box2DSystem: 'src/goo/addons/box2dpack/systems/Box2DSystem',
				CannonBoxColliderComponent: 'src/goo/addons/cannonpack/CannonBoxColliderComponent',
				CannonCylinderColliderComponent: 'src/goo/addons/cannonpack/CannonCylinderColliderComponent',
				CannonDistanceJointComponent: 'src/goo/addons/cannonpack/CannonDistanceJointComponent',
				CannonPlaneColliderComponent: 'src/goo/addons/cannonpack/CannonPlaneColliderComponent',
				CannonRigidbodyComponent: 'src/goo/addons/cannonpack/CannonRigidbodyComponent',
				CannonSphereColliderComponent: 'src/goo/addons/cannonpack/CannonSphereColliderComponent',
				CannonSystem: 'src/goo/addons/cannonpack/CannonSystem',
				CannonTerrainColliderComponent: 'src/goo/addons/cannonpack/CannonTerrainColliderComponent',
				GamepadComponent: 'src/goo/addons/gamepadpack/GamepadComponent',
				GamepadData: 'src/goo/addons/gamepadpack/GamepadData',
				GamepadSystem: 'src/goo/addons/gamepadpack/GamepadSystem',
				LineRenderer: 'src/goo/addons/linerenderpack/LineRenderer',
				LineRenderSystem: 'src/goo/addons/linerenderpack/LineRenderSystem',
				P2Component: 'src/goo/addons/p2pack/P2Component',
				P2System: 'src/goo/addons/p2pack/P2System',
				BoxCollider: 'src/goo/addons/physicspack/colliders/BoxCollider',
				Collider: 'src/goo/addons/physicspack/colliders/Collider',
				CylinderCollider: 'src/goo/addons/physicspack/colliders/CylinderCollider',
				MeshCollider: 'src/goo/addons/physicspack/colliders/MeshCollider',
				PlaneCollider: 'src/goo/addons/physicspack/colliders/PlaneCollider',
				SphereCollider: 'src/goo/addons/physicspack/colliders/SphereCollider',
				AbstractColliderComponent: 'src/goo/addons/physicspack/components/AbstractColliderComponent',
				AbstractRigidBodyComponent: 'src/goo/addons/physicspack/components/AbstractRigidBodyComponent',
				ColliderComponent: 'src/goo/addons/physicspack/components/ColliderComponent',
				RigidBodyComponent: 'src/goo/addons/physicspack/components/RigidBodyComponent',
				BallJoint: 'src/goo/addons/physicspack/joints/BallJoint',
				HingeJoint: 'src/goo/addons/physicspack/joints/HingeJoint',
				PhysicsJoint: 'src/goo/addons/physicspack/joints/PhysicsJoint',
				PhysicsMaterial: 'src/goo/addons/physicspack/PhysicsMaterial',
				RaycastResult: 'src/goo/addons/physicspack/RaycastResult',
				PhysicsBoxDebugShape: 'src/goo/addons/physicspack/shapes/PhysicsBoxDebugShape',
				PhysicsCylinderDebugShape: 'src/goo/addons/physicspack/shapes/PhysicsCylinderDebugShape',
				PhysicsPlaneDebugShape: 'src/goo/addons/physicspack/shapes/PhysicsPlaneDebugShape',
				PhysicsSphereDebugShape: 'src/goo/addons/physicspack/shapes/PhysicsSphereDebugShape',
				AbstractPhysicsSystem: 'src/goo/addons/physicspack/systems/AbstractPhysicsSystem',
				ColliderSystem: 'src/goo/addons/physicspack/systems/ColliderSystem',
				PhysicsDebugRenderSystem: 'src/goo/addons/physicspack/systems/PhysicsDebugRenderSystem',
				Pool: 'src/goo/addons/physicspack/util/Pool',
				SoundManager2Component: 'src/goo/addons/soundmanager2pack/components/SoundManager2Component',
				SoundManager2System: 'src/goo/addons/soundmanager2pack/systems/SoundManager2System',
				Forrest: 'src/goo/addons/terrainpack/Forrest',
				Terrain: 'src/goo/addons/terrainpack/Terrain',
				TerrainSurface: 'src/goo/addons/terrainpack/TerrainSurface',
				Vegetation: 'src/goo/addons/terrainpack/Vegetation',
				FlatWaterRenderer: 'src/goo/addons/waterpack/FlatWaterRenderer',
				ProjectedGrid: 'src/goo/addons/waterpack/ProjectedGrid',
				ProjectedGridWaterRenderer: 'src/goo/addons/waterpack/ProjectedGridWaterRenderer',
				BinaryLerpSource: 'src/goo/animationpack/blendtree/BinaryLerpSource',
				ClipSource: 'src/goo/animationpack/blendtree/ClipSource',
				FrozenClipSource: 'src/goo/animationpack/blendtree/FrozenClipSource',
				ManagedTransformSource: 'src/goo/animationpack/blendtree/ManagedTransformSource',
				AbstractAnimationChannel: 'src/goo/animationpack/clip/AbstractAnimationChannel',
				AnimationClip: 'src/goo/animationpack/clip/AnimationClip',
				AnimationClipInstance: 'src/goo/animationpack/clip/AnimationClipInstance',
				InterpolatedFloatChannel: 'src/goo/animationpack/clip/InterpolatedFloatChannel',
				JointChannel: 'src/goo/animationpack/clip/JointChannel',
				JointData: 'src/goo/animationpack/clip/JointData',
				TransformChannel: 'src/goo/animationpack/clip/TransformChannel',
				TransformData: 'src/goo/animationpack/clip/TransformData',
				TriggerChannel: 'src/goo/animationpack/clip/TriggerChannel',
				TriggerData: 'src/goo/animationpack/clip/TriggerData',
				AnimationComponent: 'src/goo/animationpack/components/AnimationComponent',
				Joint: 'src/goo/animationpack/Joint',
				AnimationLayer: 'src/goo/animationpack/layer/AnimationLayer',
				LayerLerpBlender: 'src/goo/animationpack/layer/LayerLerpBlender',
				Skeleton: 'src/goo/animationpack/Skeleton',
				SkeletonPose: 'src/goo/animationpack/SkeletonPose',
				AbstractState: 'src/goo/animationpack/state/AbstractState',
				AbstractTransitionState: 'src/goo/animationpack/state/AbstractTransitionState',
				FadeTransitionState: 'src/goo/animationpack/state/FadeTransitionState',
				FrozenTransitionState: 'src/goo/animationpack/state/FrozenTransitionState',
				SteadyState: 'src/goo/animationpack/state/SteadyState',
				SyncFadeTransitionState: 'src/goo/animationpack/state/SyncFadeTransitionState',
				AnimationSystem: 'src/goo/animationpack/systems/AnimationSystem',
				BoundingVolumeMeshBuilder: 'src/goo/debugpack/BoundingVolumeMeshBuilder',
				MarkerComponent: 'src/goo/debugpack/components/MarkerComponent',
				DebugDrawHelper: 'src/goo/debugpack/DebugDrawHelper',
				Debugger: 'src/goo/debugpack/Debugger',
				EntityCounter: 'src/goo/debugpack/EntityCounter',
				CameraDebug: 'src/goo/debugpack/shapes/CameraDebug',
				LightDebug: 'src/goo/debugpack/shapes/LightDebug',
				MeshRendererDebug: 'src/goo/debugpack/shapes/MeshRendererDebug',
				SkeletonDebug: 'src/goo/debugpack/shapes/SkeletonDebug',
				DebugRenderSystem: 'src/goo/debugpack/systems/DebugRenderSystem',
				MarkerSystem: 'src/goo/debugpack/systems/MarkerSystem',
				Bus: 'src/goo/entities/Bus',
				CameraComponent: 'src/goo/entities/components/CameraComponent',
				Component: 'src/goo/entities/components/Component',
				CssTransformComponent: 'src/goo/entities/components/CssTransformComponent',
				Dom3dComponent: 'src/goo/entities/components/Dom3dComponent',
				HtmlComponent: 'src/goo/entities/components/HtmlComponent',
				LightComponent: 'src/goo/entities/components/LightComponent',
				MeshDataComponent: 'src/goo/entities/components/MeshDataComponent',
				MeshRendererComponent: 'src/goo/entities/components/MeshRendererComponent',
				MovementComponent: 'src/goo/entities/components/MovementComponent',
				ParticleComponent: 'src/goo/entities/components/ParticleComponent',
				PortalComponent: 'src/goo/entities/components/PortalComponent',
				ScriptComponent: 'src/goo/entities/components/ScriptComponent',
				SoundComponent: 'src/goo/entities/components/SoundComponent',
				TextComponent: 'src/goo/entities/components/TextComponent',
				TransformComponent: 'src/goo/entities/components/TransformComponent',
				Entity: 'src/goo/entities/Entity',
				EntitySelection: 'src/goo/entities/EntitySelection',
				EntityUtils: 'src/goo/entities/EntityUtils',
				GooRunner: 'src/goo/entities/GooRunner',
				EntityManager: 'src/goo/entities/managers/EntityManager',
				Manager: 'src/goo/entities/managers/Manager',
				Selection: 'src/goo/entities/Selection',
				SystemBus: 'src/goo/entities/SystemBus',
				BoundingUpdateSystem: 'src/goo/entities/systems/BoundingUpdateSystem',
				CameraSystem: 'src/goo/entities/systems/CameraSystem',
				CssTransformSystem: 'src/goo/entities/systems/CssTransformSystem',
				Dom3dSystem: 'src/goo/entities/systems/Dom3dSystem',
				GridRenderSystem: 'src/goo/entities/systems/GridRenderSystem',
				HtmlSystem: 'src/goo/entities/systems/HtmlSystem',
				LightingSystem: 'src/goo/entities/systems/LightingSystem',
				MovementSystem: 'src/goo/entities/systems/MovementSystem',
				ParticlesSystem: 'src/goo/entities/systems/ParticlesSystem',
				PickingSystem: 'src/goo/entities/systems/PickingSystem',
				PortalSystem: 'src/goo/entities/systems/PortalSystem',
				RenderSystem: 'src/goo/entities/systems/RenderSystem',
				ScriptSystem: 'src/goo/entities/systems/ScriptSystem',
				SoundSystem: 'src/goo/entities/systems/SoundSystem',
				System: 'src/goo/entities/systems/System',
				TextSystem: 'src/goo/entities/systems/TextSystem',
				TransformSystem: 'src/goo/entities/systems/TransformSystem',
				World: 'src/goo/entities/World',
				ProximityComponent: 'src/goo/fsmpack/proximity/ProximityComponent',
				ProximitySystem: 'src/goo/fsmpack/proximity/ProximitySystem',
				Action: 'src/goo/fsmpack/statemachine/actions/Action',
				Actions: 'src/goo/fsmpack/statemachine/actions/Actions',
				AddLightAction: 'src/goo/fsmpack/statemachine/actions/AddLightAction',
				AddPositionAction: 'src/goo/fsmpack/statemachine/actions/AddPositionAction',
				AddVariableAction: 'src/goo/fsmpack/statemachine/actions/AddVariableAction',
				ApplyImpulseAction: 'src/goo/fsmpack/statemachine/actions/ApplyImpulseAction',
				ArrowsAction: 'src/goo/fsmpack/statemachine/actions/ArrowsAction',
				CollidesAction: 'src/goo/fsmpack/statemachine/actions/CollidesAction',
				CompareCounterAction: 'src/goo/fsmpack/statemachine/actions/CompareCounterAction',
				CompareCountersAction: 'src/goo/fsmpack/statemachine/actions/CompareCountersAction',
				CompareDistanceAction: 'src/goo/fsmpack/statemachine/actions/CompareDistanceAction',
				CopyJointTransformAction: 'src/goo/fsmpack/statemachine/actions/CopyJointTransformAction',
				DollyZoomAction: 'src/goo/fsmpack/statemachine/actions/DollyZoomAction',
				EmitAction: 'src/goo/fsmpack/statemachine/actions/EmitAction',
				EvalAction: 'src/goo/fsmpack/statemachine/actions/EvalAction',
				FireAction: 'src/goo/fsmpack/statemachine/actions/FireAction',
				GetPositionAction: 'src/goo/fsmpack/statemachine/actions/GetPositionAction',
				HideAction: 'src/goo/fsmpack/statemachine/actions/HideAction',
				HtmlAction: 'src/goo/fsmpack/statemachine/actions/HtmlAction',
				InBoxAction: 'src/goo/fsmpack/statemachine/actions/InBoxAction',
				IncrementCounterAction: 'src/goo/fsmpack/statemachine/actions/IncrementCounterAction',
				InFrustumAction: 'src/goo/fsmpack/statemachine/actions/InFrustumAction',
				KeyDownAction: 'src/goo/fsmpack/statemachine/actions/KeyDownAction',
				KeyPressedAction: 'src/goo/fsmpack/statemachine/actions/KeyPressedAction',
				KeyUpAction: 'src/goo/fsmpack/statemachine/actions/KeyUpAction',
				LogMessageAction: 'src/goo/fsmpack/statemachine/actions/LogMessageAction',
				LookAtAction: 'src/goo/fsmpack/statemachine/actions/LookAtAction',
				MouseDownAction: 'src/goo/fsmpack/statemachine/actions/MouseDownAction',
				MouseMoveAction: 'src/goo/fsmpack/statemachine/actions/MouseMoveAction',
				MouseUpAction: 'src/goo/fsmpack/statemachine/actions/MouseUpAction',
				MoveAction: 'src/goo/fsmpack/statemachine/actions/MoveAction',
				MultiplyVariableAction: 'src/goo/fsmpack/statemachine/actions/MultiplyVariableAction',
				NumberCompareAction: 'src/goo/fsmpack/statemachine/actions/NumberCompareAction',
				PauseAnimationAction: 'src/goo/fsmpack/statemachine/actions/PauseAnimationAction',
				PickAction: 'src/goo/fsmpack/statemachine/actions/PickAction',
				PickAndExitAction: 'src/goo/fsmpack/statemachine/actions/PickAndExitAction',
				RandomTransitionAction: 'src/goo/fsmpack/statemachine/actions/RandomTransitionAction',
				RemoveAction: 'src/goo/fsmpack/statemachine/actions/RemoveAction',
				RemoveLightAction: 'src/goo/fsmpack/statemachine/actions/RemoveLightAction',
				RemoveParticlesAction: 'src/goo/fsmpack/statemachine/actions/RemoveParticlesAction',
				ResumeAnimationAction: 'src/goo/fsmpack/statemachine/actions/ResumeAnimationAction',
				RotateAction: 'src/goo/fsmpack/statemachine/actions/RotateAction',
				ScaleAction: 'src/goo/fsmpack/statemachine/actions/ScaleAction',
				SetAnimationAction: 'src/goo/fsmpack/statemachine/actions/SetAnimationAction',
				SetClearColorAction: 'src/goo/fsmpack/statemachine/actions/SetClearColorAction',
				SetCounterAction: 'src/goo/fsmpack/statemachine/actions/SetCounterAction',
				SetLightRangeAction: 'src/goo/fsmpack/statemachine/actions/SetLightRangeAction',
				SetPositionAction: 'src/goo/fsmpack/statemachine/actions/SetPositionAction',
				SetRenderTargetAction: 'src/goo/fsmpack/statemachine/actions/SetRenderTargetAction',
				SetRotationAction: 'src/goo/fsmpack/statemachine/actions/SetRotationAction',
				SetVariableAction: 'src/goo/fsmpack/statemachine/actions/SetVariableAction',
				ShakeAction: 'src/goo/fsmpack/statemachine/actions/ShakeAction',
				ShowAction: 'src/goo/fsmpack/statemachine/actions/ShowAction',
				SmokeAction: 'src/goo/fsmpack/statemachine/actions/SmokeAction',
				SoundFadeInAction: 'src/goo/fsmpack/statemachine/actions/SoundFadeInAction',
				SoundFadeOutAction: 'src/goo/fsmpack/statemachine/actions/SoundFadeOutAction',
				SwitchCameraAction: 'src/goo/fsmpack/statemachine/actions/SwitchCameraAction',
				TagAction: 'src/goo/fsmpack/statemachine/actions/TagAction',
				TransitionAction: 'src/goo/fsmpack/statemachine/actions/TransitionAction',
				TransitionOnMessageAction: 'src/goo/fsmpack/statemachine/actions/TransitionOnMessageAction',
				TriggerEnterAction: 'src/goo/fsmpack/statemachine/actions/TriggerEnterAction',
				TriggerLeaveAction: 'src/goo/fsmpack/statemachine/actions/TriggerLeaveAction',
				TweenLightColorAction: 'src/goo/fsmpack/statemachine/actions/TweenLightColorAction',
				TweenLookAtAction: 'src/goo/fsmpack/statemachine/actions/TweenLookAtAction',
				TweenMoveAction: 'src/goo/fsmpack/statemachine/actions/TweenMoveAction',
				TweenOpacityAction: 'src/goo/fsmpack/statemachine/actions/TweenOpacityAction',
				TweenRotationAction: 'src/goo/fsmpack/statemachine/actions/TweenRotationAction',
				TweenScaleAction: 'src/goo/fsmpack/statemachine/actions/TweenScaleAction',
				TweenTextureOffsetAction: 'src/goo/fsmpack/statemachine/actions/TweenTextureOffsetAction',
				WaitAction: 'src/goo/fsmpack/statemachine/actions/WaitAction',
				WasdAction: 'src/goo/fsmpack/statemachine/actions/WasdAction',
				FSMUtil: 'src/goo/fsmpack/statemachine/FSMUtil',
				FsmUtils: 'src/goo/fsmpack/statemachine/FsmUtils',
				Machine: 'src/goo/fsmpack/statemachine/Machine',
				State: 'src/goo/fsmpack/statemachine/State',
				StateMachineComponent: 'src/goo/fsmpack/statemachine/StateMachineComponent',
				StateMachineSystem: 'src/goo/fsmpack/statemachine/StateMachineSystem',
				FilledPolygon: 'src/goo/geometrypack/FilledPolygon',
				PolyLine: 'src/goo/geometrypack/PolyLine',
				RegularPolygon: 'src/goo/geometrypack/RegularPolygon',
				Surface: 'src/goo/geometrypack/Surface',
				TextMeshGenerator: 'src/goo/geometrypack/text/TextMeshGenerator',
				Triangle: 'src/goo/geometrypack/Triangle',
				DdsUtils: 'src/goo/loaders/dds/DdsUtils',
				LogicInterface: 'src/goo/logicpack/logic/LogicInterface',
				LogicLayer: 'src/goo/logicpack/logic/LogicLayer',
				LogicNode: 'src/goo/logicpack/logic/LogicNode',
				LogicNodeAdd: 'src/goo/logicpack/logic/LogicNodeAdd',
				LogicNodeApplyMatrix: 'src/goo/logicpack/logic/LogicNodeApplyMatrix',
				LogicNodeConstVec3: 'src/goo/logicpack/logic/LogicNodeConstVec3',
				LogicNodeDebug: 'src/goo/logicpack/logic/LogicNodeDebug',
				LogicNodeEntityProxy: 'src/goo/logicpack/logic/LogicNodeEntityProxy',
				LogicNodeFloat: 'src/goo/logicpack/logic/LogicNodeFloat',
				LogicNodeInput: 'src/goo/logicpack/logic/LogicNodeInput',
				LogicNodeInt: 'src/goo/logicpack/logic/LogicNodeInt',
				LogicNodeLightComponent: 'src/goo/logicpack/logic/LogicNodeLightComponent',
				LogicNodeMax: 'src/goo/logicpack/logic/LogicNodeMax',
				LogicNodeMeshRendererComponent: 'src/goo/logicpack/logic/LogicNodeMeshRendererComponent',
				LogicNodeMouse: 'src/goo/logicpack/logic/LogicNodeMouse',
				LogicNodeMultiply: 'src/goo/logicpack/logic/LogicNodeMultiply',
				LogicNodeMultiplyFloat: 'src/goo/logicpack/logic/LogicNodeMultiplyFloat',
				LogicNodeOutput: 'src/goo/logicpack/logic/LogicNodeOutput',
				LogicNodeRandom: 'src/goo/logicpack/logic/LogicNodeRandom',
				LogicNodeRotationMatrix: 'src/goo/logicpack/logic/LogicNodeRotationMatrix',
				LogicNodes: 'src/goo/logicpack/logic/LogicNodes',
				LogicNodeSine: 'src/goo/logicpack/logic/LogicNodeSine',
				LogicNodeSub: 'src/goo/logicpack/logic/LogicNodeSub',
				LogicNodeTime: 'src/goo/logicpack/logic/LogicNodeTime',
				LogicNodeTransformComponent: 'src/goo/logicpack/logic/LogicNodeTransformComponent',
				LogicNodeVec3: 'src/goo/logicpack/logic/LogicNodeVec3',
				LogicNodeVec3Add: 'src/goo/logicpack/logic/LogicNodeVec3Add',
				LogicNodeWASD: 'src/goo/logicpack/logic/LogicNodeWASD',
				LogicNodeWASD2: 'src/goo/logicpack/logic/LogicNodeWASD2',
				LogicComponent: 'src/goo/logicpack/LogicComponent',
				LogicSystem: 'src/goo/logicpack/LogicSystem',
				Matrix: 'src/goo/math/Matrix',
				Matrix2: 'src/goo/math/Matrix2',
				Matrix2x2: 'src/goo/math/Matrix2x2',
				Matrix3: 'src/goo/math/Matrix3',
				Matrix3x3: 'src/goo/math/Matrix3x3',
				Matrix4: 'src/goo/math/Matrix4',
				Matrix4x4: 'src/goo/math/Matrix4x4',
				Plane: 'src/goo/math/Plane',
				Quaternion: 'src/goo/math/Quaternion',
				Ray: 'src/goo/math/Ray',
				Spline: 'src/goo/math/splines/Spline',
				SplineWalker: 'src/goo/math/splines/SplineWalker',
				Transform: 'src/goo/math/Transform',
				Vector: 'src/goo/math/Vector',
				Vector2: 'src/goo/math/Vector2',
				Vector3: 'src/goo/math/Vector3',
				Vector4: 'src/goo/math/Vector4',
				Noise: 'src/goo/noise/Noise',
				ValueNoise: 'src/goo/noise/ValueNoise',
				OccludeeComponent: 'src/goo/occlusionpack/OccludeeComponent',
				OccluderComponent: 'src/goo/occlusionpack/OccluderComponent',
				OcclusionPartitioner: 'src/goo/occlusionpack/OcclusionPartitioner',
				BoundingBoxOcclusionChecker: 'src/goo/occlusionpack/scanline/BoundingBoxOcclusionChecker',
				BoundingSphereOcclusionChecker: 'src/goo/occlusionpack/scanline/BoundingSphereOcclusionChecker',
				Edge: 'src/goo/occlusionpack/scanline/Edge',
				EdgeData: 'src/goo/occlusionpack/scanline/EdgeData',
				EdgeMap: 'src/goo/occlusionpack/scanline/EdgeMap',
				OccludeeTriangleData: 'src/goo/occlusionpack/scanline/OccludeeTriangleData',
				OccluderTriangleData: 'src/goo/occlusionpack/scanline/OccluderTriangleData',
				SoftwareRenderer: 'src/goo/occlusionpack/scanline/SoftwareRenderer',
				Particle: 'src/goo/particles/Particle',
				ParticleEmitter: 'src/goo/particles/ParticleEmitter',
				ParticleInfluence: 'src/goo/particles/ParticleInfluence',
				ParticleLib: 'src/goo/particles/ParticleLib',
				ParticleUtils: 'src/goo/particles/ParticleUtils',
				BloomPass: 'src/goo/passpack/BloomPass',
				BlurPass: 'src/goo/passpack/BlurPass',
				DepthPass: 'src/goo/passpack/DepthPass',
				DofPass: 'src/goo/passpack/DofPass',
				DogPass: 'src/goo/passpack/DogPass',
				MotionBlurPass: 'src/goo/passpack/MotionBlurPass',
				PassLib: 'src/goo/passpack/PassLib',
				ShaderLibExtra: 'src/goo/passpack/ShaderLibExtra',
				SsaoPass: 'src/goo/passpack/SsaoPass',
				BoundingTree: 'src/goo/picking/BoundingTree',
				PrimitivePickLogic: 'src/goo/picking/PrimitivePickLogic',
				DoubleQuad: 'src/goo/quadpack/DoubleQuad',
				QuadComponent: 'src/goo/quadpack/QuadComponent',
				BoundingBox: 'src/goo/renderer/bounds/BoundingBox',
				BoundingSphere: 'src/goo/renderer/bounds/BoundingSphere',
				BoundingVolume: 'src/goo/renderer/bounds/BoundingVolume',
				BufferData: 'src/goo/renderer/BufferData',
				BufferUtils: 'src/goo/renderer/BufferUtils',
				Camera: 'src/goo/renderer/Camera',
				Capabilities: 'src/goo/renderer/Capabilities',
				DirectionalLight: 'src/goo/renderer/light/DirectionalLight',
				Light: 'src/goo/renderer/light/Light',
				PointLight: 'src/goo/renderer/light/PointLight',
				SpotLight: 'src/goo/renderer/light/SpotLight',
				Material: 'src/goo/renderer/Material',
				MeshData: 'src/goo/renderer/MeshData',
				Composer: 'src/goo/renderer/pass/Composer',
				FullscreenPass: 'src/goo/renderer/pass/FullscreenPass',
				FullscreenUtil: 'src/goo/renderer/pass/FullscreenUtil',
				FullscreenUtils: 'src/goo/renderer/pass/FullscreenUtils',
				Pass: 'src/goo/renderer/pass/Pass',
				RenderPass: 'src/goo/renderer/pass/RenderPass',
				RenderTarget: 'src/goo/renderer/pass/RenderTarget',
				ContextLost: 'src/goo/renderer/Renderer+ContextLost',
				Renderer: 'src/goo/renderer/Renderer',
				RendererRecord: 'src/goo/renderer/RendererRecord',
				RendererUtils: 'src/goo/renderer/RendererUtils',
				RenderInfo: 'src/goo/renderer/RenderInfo',
				RenderQueue: 'src/goo/renderer/RenderQueue',
				RenderStats: 'src/goo/renderer/RenderStats',
				Shader: 'src/goo/renderer/Shader',
				ShaderCall: 'src/goo/renderer/ShaderCall',
				ShaderBuilder: 'src/goo/renderer/shaders/ShaderBuilder',
				ShaderFragment: 'src/goo/renderer/shaders/ShaderFragment',
				ShaderLib: 'src/goo/renderer/shaders/ShaderLib',
				SimplePartitioner: 'src/goo/renderer/SimplePartitioner',
				TaskScheduler: 'src/goo/renderer/TaskScheduler',
				Texture: 'src/goo/renderer/Texture',
				TextureCreator: 'src/goo/renderer/TextureCreator',
				AxisAlignedCamControlScript: 'src/goo/scriptpack/AxisAlignedCamControlScript',
				BasicControlScript: 'src/goo/scriptpack/BasicControlScript',
				ButtonScript: 'src/goo/scriptpack/ButtonScript',
				CannonPickScript: 'src/goo/scriptpack/CannonPickScript',
				FlyControlScript: 'src/goo/scriptpack/FlyControlScript',
				GroundBoundMovementScript: 'src/goo/scriptpack/GroundBoundMovementScript',
				HeightMapBoundingScript: 'src/goo/scriptpack/HeightMapBoundingScript',
				LensFlareScript: 'src/goo/scriptpack/LensFlareScript',
				MouseLookControlScript: 'src/goo/scriptpack/MouseLookControlScript',
				OrbitNPanControlScript: 'src/goo/scriptpack/OrbitNPanControlScript',
				PanCamScript: 'src/goo/scriptpack/PanCamScript',
				PickAndRotateScript: 'src/goo/scriptpack/PickAndRotateScript',
				PolyBoundingScript: 'src/goo/scriptpack/PolyBoundingScript',
				RotationScript: 'src/goo/scriptpack/RotationScript',
				ScriptRegister: 'src/goo/scriptpack/ScriptRegister',
				SparseHeightMapBoundingScript: 'src/goo/scriptpack/SparseHeightMapBoundingScript',
				WasdControlScript: 'src/goo/scriptpack/WasdControlScript',
				WorldFittedTerrainScript: 'src/goo/scriptpack/WorldFittedTerrainScript',
				OrbitCamControlScript: 'src/goo/scripts/OrbitCamControlScript',
				Scripts: 'src/goo/scripts/Scripts',
				ScriptUtils: 'src/goo/scripts/ScriptUtils',
				Box: 'src/goo/shapes/Box',
				Cone: 'src/goo/shapes/Cone',
				Cylinder: 'src/goo/shapes/Cylinder',
				Disk: 'src/goo/shapes/Disk',
				Grid: 'src/goo/shapes/Grid',
				Quad: 'src/goo/shapes/Quad',
				SimpleBox: 'src/goo/shapes/SimpleBox',
				Sphere: 'src/goo/shapes/Sphere',
				TextureGrid: 'src/goo/shapes/TextureGrid',
				Torus: 'src/goo/shapes/Torus',
				AudioContext: 'src/goo/sound/AudioContext',
				OscillatorSound: 'src/goo/sound/OscillatorSound',
				Sound: 'src/goo/sound/Sound',
				AbstractTimelineChannel: 'src/goo/timelinepack/AbstractTimelineChannel',
				EventChannel: 'src/goo/timelinepack/EventChannel',
				TimelineComponent: 'src/goo/timelinepack/TimelineComponent',
				TimelineSystem: 'src/goo/timelinepack/TimelineSystem',
				ValueChannel: 'src/goo/timelinepack/ValueChannel',
				Ajax: 'src/goo/util/Ajax',
				ArrayUtil: 'src/goo/util/ArrayUtil',
				ArrayUtils: 'src/goo/util/ArrayUtils',
				CanvasUtils: 'src/goo/util/CanvasUtils',
				AtlasNode: 'src/goo/util/combine/AtlasNode',
				EntityCombiner: 'src/goo/util/combine/EntityCombiner',
				Rectangle: 'src/goo/util/combine/Rectangle',
				EventTarget: 'src/goo/util/EventTarget',
				GameUtils: 'src/goo/util/GameUtils',
				Gizmo: 'src/goo/util/gizmopack/Gizmo',
				GizmoRenderSystem: 'src/goo/util/gizmopack/GizmoRenderSystem',
				GlobalRotationGizmo: 'src/goo/util/gizmopack/GlobalRotationGizmo',
				GlobalTranslationGizmo: 'src/goo/util/gizmopack/GlobalTranslationGizmo',
				RotationGizmo: 'src/goo/util/gizmopack/RotationGizmo',
				ScaleGizmo: 'src/goo/util/gizmopack/ScaleGizmo',
				TranslationGizmo: 'src/goo/util/gizmopack/TranslationGizmo',
				Logo: 'src/goo/util/Logo',
				MeshBuilder: 'src/goo/util/MeshBuilder',
				ObjectUtil: 'src/goo/util/ObjectUtil',
				ObjectUtils: 'src/goo/util/ObjectUtils',
				ParticleSystemUtils: 'src/goo/util/ParticleSystemUtils',
				PromiseUtil: 'src/goo/util/PromiseUtil',
				PromiseUtils: 'src/goo/util/PromiseUtils',
				Rc4Random: 'src/goo/util/Rc4Random',
				rsvp: 'src/goo/util/rsvp',
				ShapeCreatorMemoized: 'src/goo/util/ShapeCreatorMemoized',
				Skybox: 'src/goo/util/Skybox',
				Snow: 'src/goo/util/Snow',
				SoundCreator: 'src/goo/util/SoundCreator',
				Stats: 'src/goo/util/Stats',
				StringUtil: 'src/goo/util/StringUtil',
				StringUtils: 'src/goo/util/StringUtils',
				TangentGenerator: 'src/goo/util/TangentGenerator',
				TWEEN: 'src/goo/util/TWEEN',
			})
		]
	},

	// optionally, configure the reporter
	/*
	coverageReporter: {
		type : 'html',
		dir : 'coverage/'
	},
	*/

	webpackMiddleware: {
		// webpack-dev-middleware configuration
		// i. e.
		noInfo: true
	}
  });
};
